script: bundle exec rake SPEC_OPTS="--tag ~travis" spec
before_script: bundle exec rake ci:before
language: ruby
services: mysql
rvm:
  - jruby-1.7.10
  - jruby-head
jdk:
  - openjdk6
  - openjdk7
matrix:
  exclude:
    - rvm: jruby-head
      jdk: openjdk6
