development:
  adapter: mysql
  database: rearview_ruby_development
  username: root
  password:
  host: localhost

test:
  adapter: mysql
  database: rearview_ruby_test
  username: root
  password:
  host: localhost

production:
  adapter: mysql
  database: rearview_ruby_production
  username: root
  password:
  host: localhost
